[project]
name = "bo4mob"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "botorch==0.13.0",
    "lxml==5.3.1",
    "matplotlib==3.10.1",
    "numpy==2.2.4",
    "pandas==2.2.3",
    "torch==2.6.0",
]


[tool.setuptools.package-data]
"bo4mob" = ["config/*", "network/**/*", "od_for_single_run/*", "sensor_data/**/*"]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
